FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --production=true && npm cache clean --force
COPY .medusa ./.medusa
RUN cp .medusa/server/medusa-config.js ./medusa-config.js && \
    cp -r .medusa/server/src ./src && \
    mkdir -p public/admin && \
    cp -r .medusa/server/public/admin/. ./public/admin/
EXPOSE 9000
CMD ["sh", "-c", "npx medusa db:migrate && npx medusa start"]
